//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseTHP.StoredProcedure
{
    using System;
    
    public partial class Sp_Get_DanhSachHangHoa
    {
        public string ID { get; set; }
        public string MA { get; set; }
        public string NAME { get; set; }
        public string ID_GROUP { get; set; }
        public string MA_GROUP { get; set; }
        public string NAME_GROUP { get; set; }
        public string ID_HANGHOA { get; set; }
        public string MA_HANGHOA { get; set; }
        public string NAME_HANGHOA { get; set; }
        public string ID_DVT { get; set; }
        public string MA_DVT { get; set; }
        public string NAME_DVT { get; set; }
        public string ID_DVT_QD { get; set; }
        public string MA_DVT_QD { get; set; }
        public string NAME_DVT_QD { get; set; }
        public double TYLE_QD { get; set; }
        public double SOLUONG_MUA { get; set; }
        public double TONGCONG_MUA { get; set; }
        public double DONGIA { get; set; }
        public string NAME_SOLUONG_MUA
        {
            get
            {
                int PhanNguyen = 0;
                if (TYLE_QD == 0)
                    TYLE_QD = 1;
                PhanNguyen = Convert.ToInt32(SOLUONG_MUA) / Convert.ToInt32(TYLE_QD);
                return DONGIA.ToString("N0") + " - "+ (PhanNguyen > 0 ? PhanNguyen.ToString("N0") + " " + NAME_DVT : "") + ((Convert.ToDecimal(SOLUONG_MUA) - Convert.ToDecimal(PhanNguyen * TYLE_QD)) > 0 ? (" " + (Convert.ToDecimal(SOLUONG_MUA) - Convert.ToDecimal(PhanNguyen * TYLE_QD)).ToString("N0") + " " + NAME_DVT_QD) : "");
            }
            set
            {

            }
        }

        public double SOLUONG_TRAHANG { get; set; }
        public double TONGCONG_TRAHANG { get; set; }


        public string NAME_SOLUONG_TRAHANG
        {
            get
            {
                int PhanNguyen = 0;
                if (TYLE_QD == 0)
                    TYLE_QD = 1;
                PhanNguyen = Convert.ToInt32(SOLUONG_TRAHANG) / Convert.ToInt32(TYLE_QD);
                return (PhanNguyen > 0 ? PhanNguyen.ToString("N0") + " " + NAME_DVT : "") + ((Convert.ToDecimal(SOLUONG_TRAHANG) - Convert.ToDecimal(PhanNguyen * TYLE_QD)) > 0 ? (" " + (Convert.ToDecimal(SOLUONG_TRAHANG) - Convert.ToDecimal(PhanNguyen * TYLE_QD)).ToString("N0") + " " + NAME_DVT_QD) : "");
            }
            set
            {

            }
        }
        public double TONGCONG_CONLAI
        {
            get
            {
                return TONGCONG_MUA - TONGCONG_TRAHANG;
            }
            set
            {

            }
        }
        public string NAME_SOLUONG_CONLAI
        {
            get
            {
                int PhanNguyen = 0;
                if (TYLE_QD == 0)
                    TYLE_QD = 1;
                PhanNguyen = Convert.ToInt32(SOLUONG_MUA - SOLUONG_TRAHANG) / Convert.ToInt32(TYLE_QD);
                return (PhanNguyen > 0 ? PhanNguyen.ToString("N0") + " " + NAME_DVT : "") + ((Convert.ToDecimal(SOLUONG_MUA - SOLUONG_TRAHANG) - Convert.ToDecimal(PhanNguyen * TYLE_QD)) > 0 ? (" " + (Convert.ToDecimal(SOLUONG_MUA - SOLUONG_TRAHANG) - Convert.ToDecimal(PhanNguyen * TYLE_QD)).ToString("N0") + " " + NAME_DVT_QD) : "");
            }
            set
            {

            }
        }
    }
}
