//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseTHP.StoredProcedure
{
    using System;
    
    public partial class Sp_Get_DanhSachPhieuXuatHang_KhuyenMai : ct_PhieuXuat_ChiTiet
    {
        public string NAME_DVT { get; set; }
        public string NAME_DVT_QD { get; set; }
        public string ID_KHUVUC { get; set; }
        public string MA_KHUVUC { get; set; }
        public string NAME_KHUVUC { get; set; }
        public string MA_KHACHHANG { get; set; }
        public string NAME_KHACHHANG { get; set; }
        public string MA_CHUONGTRINHKHUYENMAI { get; set; }
        public string NAME_CHUONGTRINHKHUYENMAI { get; set; }
        public string ID_HANGHOA { get; set; }
        public string MA_HANGHOA { get; set; }
        public string NAME_HANGHOA { get; set; }
        public string ID_NHOMHANGHOA { get; set; }
        public string MA_NHOMHANGHOA { get; set; }
        public string NAME_NHOMHANGHOA { get; set; }
        public string ADDRESS { get; set; }
        public string TEL { get; set; }
        public double TONGSOLUONG_TRAHANG { get; set; }
        public double TONGCONG_TRAHANG { get; set; }
        public double TONGTIENGIAMGIA_TRAHANG { get; set; }
        public double THANHTIEN_TRAHANG { get; set; }
        public double TONGTIEN_TRAHANG { get; set; }
    }

}
