//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseTHP.StoredProcedure
{
    using System;
    
    public partial class view_nv_BangLuong
    {
        public string MAPHIEU { get; set; }
        public int SOPHIEU { get; set; }
        public string LOC_ID { get; set; }
        public string ID { get; set; }
        public string ID_THANGLUONG { get; set; }
        public string ID_NHANVIEN { get; set; }
        public double SONGAYCONG { get; set; }
        public double MUCLUONG { get; set; }
        public double SONGAYLAMVIEC { get; set; }
        public double SONGAYNGHIPHEP { get; set; }
        public double TIENLUONG { get; set; }
        public double TIENLUONGKHAC { get; set; }
        public double TIENGIAM { get; set; }
        public double TIENTHUCNHAN { get; set; }
        public string GHICHU { get; set; }
        public DateTime NGAYLAP { get; set; }
        public Boolean ISTINHLUONG { get; set; }
        public double LUONGCOBAN { get; set; }
        public DateTime NGAYBATDAU { get; set; }
        public DateTime NGAYKETTHUC { get; set; }    
        public double THANG { get; set; }
        public double NAM { get; set; }
        public double SONGAY { get; set; }
        public string THANGNAM
        {
            get
            {
                return THANG.ToString() + "/" + NAM.ToString();
            }
        }
        public double NAMTHANG_ORDERBY
        {
            get
            {
                return (NAM * 100) + THANG;
            }
        }
        public string MA_NHANVIEN { get; set; }
        public string NAME_NHANVIEN { get; set; }
        public string MA_THANGLUONG { get; set; }
        public string NAME_THANGLUONG { get; set; }
        public DateTime? THOIGIANSUA { get; set; }
        public string ID_NGUOISUA { get; set; }
        public DateTime? THOIGIANTHEM { get; set; }
        public string ID_NGUOITAO { get; set; }
        public double SONGAYNGHIKHONGPHEP { get; set; }
        public double TIENDAUKY { get; set; }
    }
}
